# Generated by Django 6.0.2 on 2026-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
