# Generated by Django 6.0.2 on 2026-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0004_rename_date_task_due_date_task_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='to-do', max_length=20),
        ),
    ]
