# Generated by Django 6.0.2 on 2026-03-04 09:37

import django.db.models.deletion
from django.db import migrations, models


def clean_empty_fk_strings(apps, schema_editor): # Diese Funktion setzt alle leeren Strings in den Feldern 'assignee' und 'reviewer' der Tabelle 'mental_task' auf NULL, damit die Umwandlung von CharField zu ForeignKey reibungslos funktioniert.
    connection = schema_editor.connection
    cursor = connection.cursor()
    cursor.execute("UPDATE mental_task SET assignee = NULL WHERE assignee = ''")
    cursor.execute("UPDATE mental_task SET reviewer = NULL WHERE reviewer = ''")


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0008_remove_task_comments_comment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='added_members',
            field=models.ManyToManyField(blank=True, related_name='added_boards', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.RunPython(clean_empty_fk_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to='users.userprofile'),
        ),
    ]
